/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRCAP_H_RPCGEN
#define _STRCAP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x41320021
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STRDATE 2
extern  char ** strdate_1(char **, CLIENT *);
extern  char ** strdate_1_svc(char **, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STRDATE 2
extern  char ** strdate_1();
extern  char ** strdate_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRCAP_H_RPCGEN */
